Package: dpi
Version: 1.0.0
Revision: 1
Maintainer: Game Master <gamemaster@101gr.com>
Description: |
 DPI module allows to detect device DPI
Homepage: https://github.com/marmalade/dpi
Type: platform-independant
Contents:
 - dpi.mkf
 - src
 - h
 - README
#Contents-platform:
# win32:
#  - lib/x86/README